#!/usr/bin/env python3
"""Living content ledger for the CA Foundation QA pack.

Single source of truth for: how many questions we have, how many each
generation attempt produced, and how many failed / were corrected / were
regenerated. Scans the promoted items plus every per-run `summary.json` under
`packs/ca-foundation-qa/audit/`, and rewrites `packs/ca-foundation-qa/audit/STATUS.md`.

Re-run after every generation attempt (and it is safe to wire into
build_and_validate.py): each run drops a normalized `audit/<run>/summary.json`,
and this script aggregates them. Detailed per-item funnels live alongside in
`funnel_report.json`; this is the rollup.

    python3 tools/content_status.py
"""
import json
import glob
import pathlib
import datetime
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACK = ROOT / "packs" / "ca-foundation-qa"
ITEMS = PACK / "items"
AUDIT = PACK / "audit"
TAX = json.loads((ROOT / "schema/profiles/ca-foundation-qa/taxonomy.json").read_text())


def section(node):
    if node.startswith("qa.bmath.ratio_indices_log") or node.startswith("qa.bmath.equations") or node.startswith("qa.bmath.inequalities"):
        return "I  Ratio/Equations/Inequalities"
    if node.startswith("qa.bmath.finance"):
        return "II  Mathematics of Finance"
    if node.startswith("qa.bmath"):
        return "III  P&C/Sequence/Sets/Calculus"
    if node.startswith("qa.lr"):
        return "IV  Logical Reasoning"
    if node.startswith("qa.stats.data_representation") or node.startswith("qa.stats.central_tendency_dispersion"):
        return "V  Data rep + Central tendency"
    if node.startswith("qa.stats.probability") or node.startswith("qa.stats.distributions"):
        return "VI  Probability + Distributions"
    if node.startswith("qa.stats.correlation_regression"):
        return "VII  Correlation & Regression"
    if node.startswith("qa.stats.index_numbers"):
        return "VIII  Index Numbers"
    return "?"


def main():
    items = [json.loads(p.read_text()) for p in sorted(ITEMS.glob("*.json"))]
    served = [i for i in items if i.get("verification_status") != "retired"]
    total = len(served)
    diff = Counter(i["difficulty_label"] for i in served)
    secs = Counter(section(i["tests"][0]) for i in served)

    nodes = TAX["nodes"]
    parents = {n["parent"] for n in nodes if n["parent"]}
    leaves = [n["id"] for n in nodes if n["id"] not in parents and not n.get("abstract")]
    cov = Counter(i["tests"][0] for i in served)
    covered = sum(1 for l in leaves if cov.get(l, 0) > 0)
    depths = sorted(cov.get(l, 0) for l in leaves)
    med = depths[len(depths) // 2] if depths else 0

    runs = []
    for p in sorted(AUDIT.glob("*/summary.json")):
        runs.append(json.loads(p.read_text()))

    def s(r, k):
        return r.get(k, 0) or 0

    cum = {k: sum(s(r, k) for r in runs) for k in
           ("generated", "accepted", "first_pass_clean", "edited", "regenerated",
            "dropped", "wrong_answer_rejections", "non_original_rejections")}

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    L = []
    L.append("# Content status — CA Foundation QA")
    L.append("")
    L.append(f"_Living ledger. Regenerated by `tools/content_status.py`. Last updated: {now}._")
    L.append("")
    L.append("## The bank right now")
    L.append("")
    L.append(f"- **Total served questions: {total}**")
    # Round, do not floor: floor division published a mix summing to 98%.
    L.append(f"- Difficulty: L1 {diff['L1']} ({round(100*diff['L1']/total)}%) / L2 {diff['L2']} ({round(100*diff['L2']/total)}%) / L3 {diff['L3']} ({round(100*diff['L3']/total)}%)  (ICAI reference 26/66/8)")
    L.append(f"- Leaf coverage: {covered}/{len(leaves)} v1-scope leaves have items (median {med} per leaf)")
    L.append("")
    L.append("By ICAI section:")
    L.append("")
    L.append("| Section | Items |")
    L.append("|---|---|")
    for sname in sorted(secs):
        L.append(f"| {sname} | {secs[sname]} |")
    L.append("")
    L.append("## Generation attempts")
    L.append("")
    L.append("Every authoring run is gated by: solution harness (the answer must be reproduced by executable code), Tier-1/Tier-2 schema and cross-record lint, originality vs the pack and the ICAI-modelled vault, and — for hard runs — an adversarial difficulty audit. Failures are corrected in place or regenerated; nothing ships on trust.")
    L.append("")
    L.append("| Run | Date | Generated | Clean 1st pass | Edited | Regenerated | Genuine L3 | Wrong answer | Non-original | Notes |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in runs:
        gl3 = r.get("genuine_l3")
        gl3 = "-" if gl3 is None else gl3
        L.append("| {run} | {date} | {generated} | {first_pass_clean} | {edited} | {regenerated} | {gl3} | {wrong_answer_rejections} | {non_original_rejections} | {notes} |".format(
            run=r.get("run", "?"), date=r.get("date", ""), generated=s(r, "generated"),
            first_pass_clean=s(r, "first_pass_clean"), edited=s(r, "edited"),
            regenerated=s(r, "regenerated"), gl3=gl3,
            wrong_answer_rejections=s(r, "wrong_answer_rejections"),
            non_original_rejections=s(r, "non_original_rejections"), notes=r.get("notes", "")))
    L.append("| **Cumulative** | | **{generated}** | **{first_pass_clean}** | **{edited}** | **{regenerated}** | | **{wrong_answer_rejections}** | **{non_original_rejections}** | |".format(**cum))
    L.append("")
    L.append("## The two numbers we hold ourselves to")
    L.append("")
    L.append(f"- **Questions shipped with a wrong answer key: {cum['wrong_answer_rejections']}** — every answer is reproduced by an executable solution before it ships.")
    L.append(f"- **Questions shipped that were not original: {cum['non_original_rejections']}** — every stem is checked for overlap against our own bank and the ICAI-modelled reference.")
    L.append("")
    L.append("Baseline: the bank began at 106 calibrated items that predate these runs; the runs above account for the rest.")
    L.append("")
    (AUDIT / "STATUS.md").write_text("\n".join(L) + "\n")
    print(f"wrote {AUDIT / 'STATUS.md'}  ({total} items, {len(runs)} runs)")


if __name__ == "__main__":
    main()
